import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
const root=path.resolve(import.meta.dirname,'..');
const source=path.join(root,'vendor','SillyTavern');
const require=createRequire(path.join(source,'package.json'));
const archiver=require('archiver');
const yaml=require('yaml');
const packageInfo=require(path.join(source,'package.json'));
const config=yaml.parse(fs.readFileSync(path.join(source,'default','config.yaml'),'utf8'));
config.browserLaunch.enabled=false;
config.listen=false;
config.port=8787;
config.performance.lazyLoadCharacters=true;
config.performance.memoryCacheCapacity='32mb';
config.performance.useDiskCache=false;
const dest=path.join(root,'app','src','main','assets','tavern.zip');
fs.mkdirSync(path.dirname(dest),{recursive:true});
const out=fs.createWriteStream(dest);
const zip=archiver('zip',{zlib:{level:6}});
zip.on('warning', error=>{throw error});
zip.on('error', error=>{throw error});
zip.pipe(out);
zip.glob('**/*',{cwd:source,dot:true,ignore:['.git/**','data/**','config.yaml','node_modules/.bin/**','node_modules/**/*.node','node_modules/@img/**','node_modules/onnxruntime-node/**']});
zip.append(yaml.stringify(config),{name:'config.yaml'});
await zip.finalize();
await new Promise((resolve,reject)=>{out.on('close',resolve);out.on('error',reject)});
const assets=path.join(root,'app','src','main','assets');
fs.copyFileSync(path.join(source,'src','endpoints','characters.js'),path.join(assets,'android-characters.js'));
fs.writeFileSync(path.join(assets,'android-characters.version'),String(packageInfo.version));
console.log(`Packed ${zip.pointer()} bytes to ${dest}`);
